import { useState, useEffect } from 'react'
import { getSessionId } from '../utils/session'
import DynamicChart from './DynamicChart'
import { KpiCard, InsightCard } from './SharedComponents'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

export default function FullReportWidget({ onComplete }) {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [exporting, setExporting] = useState(false)

  useEffect(() => {
    async function fetchReport() {
      try {
        const res = await fetch('/api/auto-report', {
          method: 'POST',
          headers: { 'X-Session-ID': getSessionId() }
        })
        if (!res.ok) throw new Error('Failed to generate auto-report')
        const json = await res.json()
        setData(json)
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }
    fetchReport()
  }, [])

  async function handleExport() {
    if (!data) return
    setExporting(true)
    try {
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const primaryColor = [26, 86, 219]

      // 1. Cover Page
      pdf.setFontSize(24)
      pdf.setTextColor(...primaryColor)
      pdf.text('Comprehensive Business Insights Report', 20, 40)
      
      pdf.setFontSize(12)
      pdf.setTextColor(75, 85, 99)
      pdf.text(`Generated by InsightFlow AI on ${new Date().toLocaleDateString()}`, 20, 50)

      pdf.setFontSize(14)
      pdf.setTextColor(17, 24, 39)
      pdf.text('Executive Summary', 20, 75)
      
      pdf.setFontSize(11)
      pdf.setTextColor(55, 65, 81)
      const summaryLines = pdf.splitTextToSize(data.insight || 'No summary available.', pageW - 40)
      pdf.text(summaryLines, 20, 85)

      // 2. Charts Pages
      const chartElements = document.querySelectorAll('.report-chart-card')
      for (let i = 0; i < chartElements.length; i++) {
        pdf.addPage()
        
        const el = chartElements[i]
        const title = el.getAttribute('data-title') || `Insight ${i+1}`
        
        pdf.setFontSize(14)
        pdf.setTextColor(...primaryColor)
        pdf.text(title, 20, 15)

        const dataUrl = await toPng(el, { backgroundColor: '#ffffff', pixelRatio: 2 })
        const imgProps = pdf.getImageProperties(dataUrl)
        const ratio = Math.min((pageW - 40) / imgProps.width, (pageH - 40) / imgProps.height)
        pdf.addImage(dataUrl, 'PNG', 20, 25, imgProps.width * ratio, imgProps.height * ratio)
      }

      pdf.save(`insightflow-full-report-${Date.now()}.pdf`)
      if (onComplete) onComplete()
    } catch (err) {
      alert('Report export failed: ' + err.message)
    } finally {
      setExporting(false)
    }
  }

  if (loading) return (
    <div className="report-overlay">
      <div className="report-modal">
        <div className="pipeline-progress">
          <div className="pipeline-label">Generating Comprehensive Report...</div>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>AI is analyzing trends, distributions, and calculating KPIs across your entire dataset.</p>
          <div className="loading-spinner" style={{ margin: '20px auto' }}></div>
        </div>
      </div>
    </div>
  )

  if (error) return (
    <div className="report-overlay">
      <div className="report-modal">
        <h3>Report Generation Failed</h3>
        <p className="error-text">{error}</p>
        <button className="btn btn-secondary" onClick={onComplete}>Close</button>
      </div>
    </div>
  )

  return (
    <div className="report-overlay">
      <div className="report-modal full-report-view">
        <div className="modal-header">
          <h3>AI Business Report</h3>
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-primary btn-sm" onClick={handleExport} disabled={exporting}>
              {exporting ? '⏳ Exporting...' : '⬇ Download PDF Report'}
            </button>
            <button className="btn btn-ghost btn-sm" onClick={onComplete}>✕ Close</button>
          </div>
        </div>

        <div className="report-content" id="report-content">
          <div className="report-section">
            <h4>Executive Summary</h4>
            <InsightCard text={data.insight} />
          </div>

          <div className="report-kpis">
            {data.kpis?.map((k, i) => (
              <KpiCard key={i} label={k.label} value={k.value} format={k.format} />
            ))}
          </div>

          <div className="report-charts-grid">
            {data.charts?.map((chart, i) => (
              <div key={i} className="chart-card report-chart-card" data-title={chart.title}>
                <h5>{chart.title}</h5>
                <DynamicChart 
                  type={chart.type} rows={chart.rows} 
                  xCol={chart.x_col} yCols={chart.y_cols} 
                  colorCol={chart.color_col} 
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
